version: '3.8'

volumes:
  pg_data:

services:
  db:
    image: postgres:14.1-alpine
    container_name: postgres
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    ports:
      - 5432:5432

  redis_token:
    image: redis:7.2-rc2
    container_name: redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    restart: on-failure
    env_file:
      - .env
    ports:
      - 6379:6379

#  app:
#    build: .
#    container_name: app
#    env_file:
#      - .env
#    depends_on:
#      - redis_token
#      - db
#    ports:
#      - 8000:8000


