version: '3.8'

volumes:
  pg_data:

services:
  db:
    image: postgres:14.1-alpine
    container_name: postgres
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
